//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.HospitalAddress1 = new HashSet<HospitalAddress>();
            this.ProductEntity = new HashSet<ProductEntity>();
            this.Request = new HashSet<Request>();
        }
    
        public int HospitalId { get; set; }
        public string HospitalName { get; set; }
        public Nullable<int> DomainScopeID { get; set; }
        public Nullable<int> HospitalTypeID { get; set; }
        public string HospitalAddress { get; set; }
        public Nullable<int> HospitalCityId { get; set; }
        public string FaxNumber { get; set; }
        public string HospitalLandLineNo { get; set; }
        public string RegistrationNumber { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNumber { get; set; }
        public Nullable<bool> IsContactNumberVerified { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string HospitalEmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual City City { get; set; }
        public virtual DomainScope DomainScope { get; set; }
        public virtual HospitalType HospitalType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalAddress> HospitalAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntity> ProductEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
