//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequest()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PurchaseRequestId { get; set; }
        public Nullable<int> ParentRequestForQuoteId { get; set; }
        public Nullable<int> ProductEntityId { get; set; }
        public Nullable<int> AssignedToUserId { get; set; }
        public Nullable<int> AssignedByUserId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductEntity ProductEntity { get; set; }
        public virtual RequestForQuote RequestForQuote { get; set; }
        public virtual Status Status { get; set; }
    }
}
