//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int ResponseId { get; set; }
        public Nullable<int> TissueBankId { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string ResponseBody { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual TissueBank TissueBank { get; set; }
    }
}
