//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaggedNotification
    {
        public int TaggedNotificationId { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public Nullable<int> NotificationTagId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual NotificationTag NotificationTag { get; set; }
    }
}
