//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TissueBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TissueBank()
        {
            this.ProductEntity = new HashSet<ProductEntity>();
            this.Response = new HashSet<Response>();
            this.TissueBankProduct = new HashSet<TissueBankProduct>();
        }
    
        public int TissueBankId { get; set; }
        public string TissueBankName { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNumber { get; set; }
        public string TissueBankEmailId { get; set; }
        public string BusinessURL { get; set; }
        public Nullable<bool> IsMobileVerified { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string TissueBankAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public string TissueBankStateLicense { get; set; }
        public string CustomerServiceLandLineNumber { get; set; }
        public string FaxNumber { get; set; }
        public string TaxPayerId { get; set; }
        public string AATBLicenseNumber { get; set; }
        public Nullable<System.DateTime> AATBExpirationDate { get; set; }
        public Nullable<System.DateTime> AATBAccredationDate { get; set; }
        public Nullable<bool> IsAllocatMember { get; set; }
        public Nullable<bool> IsAccountVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntity> ProductEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TissueBankProduct> TissueBankProduct { get; set; }
    }
}
