//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TissueBankProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TissueBankProduct()
        {
            this.ProductEntity = new HashSet<ProductEntity>();
        }
    
        public int TissueBankProductId { get; set; }
        public Nullable<int> TissueBankId { get; set; }
        public Nullable<int> ProductMasterId { get; set; }
        public string ProductType { get; set; }
        public string ProductCode { get; set; }
        public string ProductSize { get; set; }
        public string PreservationType { get; set; }
        public string ProductDescription { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<bool> IsAvailableForSale { get; set; }
        public Nullable<System.DateTime> AvailabilityStartDate { get; set; }
        public Nullable<System.DateTime> AvailabilityEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntity> ProductEntity { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual Source Source { get; set; }
        public virtual TissueBank TissueBank { get; set; }
    }
}
